#!/usr/bin/env python3
"""
Standalone script to plot geometry analysis data from CSV files.

This script reads CSV files generated by analyze_geometry.py and creates
plots of the geometric parameters over time (or frame number).

Usage:
    # Plot single column from single file
    python3 plot_geometry.py data.csv output.png
    
    # Plot specific columns from single file
    python3 plot_geometry.py data.csv output.png --columns 0 1
    
    # Plot multiple files for comparison
    python3 plot_geometry.py file1.csv file2.csv file3.csv output.png --columns 0
    
    # Customize plot
    python3 plot_geometry.py data.csv output.png --xlabel "Frame" --ylabel "Bond Length (Å)" --title "Bond Length Evolution"
"""

import argparse
import numpy as np
import matplotlib.pyplot as plt
import os
import sys


def read_csv_no_header(filename):
    """
    Read CSV file without header (just numeric data).
    
    Returns:
        numpy array with shape (n_frames, n_columns)
    """
    data = np.loadtxt(filename, delimiter=',')
    # Handle single column case
    if data.ndim == 1:
        data = data.reshape(-1, 1)
    return data


def main():
    parser = argparse.ArgumentParser(
        description="Plot geometry analysis data from CSV files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    
    parser.add_argument(
        'input_csv',
        type=str,
        nargs='+',
        help='Input CSV file(s) (from analyze_geometry.py, no header). Can specify multiple files for comparison.'
    )
    
    parser.add_argument(
        'output_png',
        type=str,
        help='Output PNG file'
    )
    
    parser.add_argument(
        '--columns',
        type=int,
        nargs='+',
        default=None,
        help='Column indices to plot (0-indexed). Applies to all files. If not specified, plots column 0 from each file.'
    )
    
    parser.add_argument(
        '--xlabel',
        type=str,
        default='time (fs)',
        help='X-axis label (default: "time (fs)")'
    )
    
    parser.add_argument(
        '--ylabel',
        type=str,
        default=None,
        help='Y-axis label. If not specified, uses "Value" or column-specific labels if --labels provided.'
    )
    
    parser.add_argument(
        '--labels',
        type=str,
        nargs='+',
        default=None,
        help='Labels for each file-column combination (legend). Format: one label per file (if single column) or per file-column pair. If not specified, uses filenames.'
    )
    
    parser.add_argument(
        '--title',
        type=str,
        default=None,
        help='Plot title'
    )
    
    parser.add_argument(
        '--xmin',
        type=float,
        default=None,
        help='Minimum x-axis value'
    )
    
    parser.add_argument(
        '--xmax',
        type=float,
        default=None,
        help='Maximum x-axis value'
    )
    
    parser.add_argument(
        '--ymin',
        type=float,
        default=None,
        help='Minimum y-axis value'
    )
    
    parser.add_argument(
        '--ymax',
        type=float,
        default=None,
        help='Maximum y-axis value'
    )
    
    parser.add_argument(
        '--figsize',
        type=float,
        nargs=2,
        default=[10, 6],
        metavar=('WIDTH', 'HEIGHT'),
        help='Figure size in inches (default: 10 6)'
    )
    
    parser.add_argument(
        '--dpi',
        type=int,
        default=300,
        help='Output resolution in DPI (default: 300)'
    )
    
    parser.add_argument(
        '--style',
        type=str,
        choices=['line', 'scatter', 'both'],
        default='line',
        help='Plot style: line, scatter, or both (default: line)'
    )
    
    parser.add_argument(
        '--grid',
        action='store_true',
        help='Show grid on plot'
    )
    
    args = parser.parse_args()
    
    # Check all input files exist
    for input_file in args.input_csv:
        if not os.path.exists(input_file):
            print(f"Error: Input file '{input_file}' not found.")
            sys.exit(1)
    
    # Read all data files
    all_data = []
    for input_file in args.input_csv:
        try:
            data = read_csv_no_header(input_file)
            all_data.append(data)
            n_frames, n_columns = data.shape
            print(f"Read {n_frames} frames with {n_columns} column(s) from {input_file}")
        except Exception as e:
            print(f"Error reading CSV file '{input_file}': {e}")
            sys.exit(1)
    
    # Determine which columns to plot (applies to all files)
    if args.columns is None:
        # Default: plot column 0 from each file
        columns_to_plot = [0]
    else:
        columns_to_plot = args.columns
    
    # Validate column indices for all files
    for file_idx, data in enumerate(all_data):
        n_frames, n_columns = data.shape
        for col in columns_to_plot:
            if col < 0 or col >= n_columns:
                print(f"Error: Column index {col} is out of range (0-{n_columns-1}) for file {args.input_csv[file_idx]}")
                sys.exit(1)
    
    n_plots = len(args.input_csv) * len(columns_to_plot)
    if n_plots == 0:
        print("Error: No columns to plot")
        sys.exit(1)
    
    # Generate labels if not provided
    if args.labels is None:
        labels = []
        for file_idx, input_file in enumerate(args.input_csv):
            base_name = os.path.splitext(os.path.basename(input_file))[0]
            for col_idx in columns_to_plot:
                if len(columns_to_plot) == 1:
                    labels.append(base_name)
                else:
                    labels.append(f"{base_name} (col {col_idx})")
    else:
        labels = args.labels
        if len(labels) != n_plots:
            print(f"Error: Number of labels ({len(labels)}) does not match number of plots ({n_plots})")
            print(f"Expected {n_plots} labels for {len(args.input_csv)} file(s) × {len(columns_to_plot)} column(s)")
            sys.exit(1)
    
    # Create figure
    fig, ax = plt.subplots(figsize=args.figsize)
    
    # Plot each file and column combination
    plot_idx = 0
    for file_idx, data in enumerate(all_data):
        n_frames = data.shape[0]
        # Convert frame numbers to time in fs (each frame = 20 fs, first frame at 10 fs)
        x = np.arange(n_frames) * 20.0 + 10.0
        
        for col_idx in columns_to_plot:
            y = data[:, col_idx]
            label = labels[plot_idx]
            
            if args.style == 'line':
                ax.plot(x, y, label=label, linewidth=2)
            elif args.style == 'scatter':
                ax.scatter(x, y, label=label, s=20, alpha=0.7)
            else:  # both
                ax.plot(x, y, label=label, linewidth=2, alpha=0.7)
                ax.scatter(x, y, s=20, alpha=0.5)
            
            plot_idx += 1
    
    # Set labels and title
    ax.set_xlabel(args.xlabel)
    if args.ylabel:
        ax.set_ylabel(args.ylabel)
    else:
        ax.set_ylabel('Value')
    
    if args.title:
        ax.set_title(args.title)
    
    # Set axis limits
    # Default xmin to 0 to show blank space before first frame (which starts at 10 fs)
    if args.xmin is not None:
        xmin = args.xmin
    else:
        xmin = 0.0
    if args.xmax is not None:
        xmax = args.xmax
    else:
        xmax = None
    ax.set_xlim(left=xmin, right=xmax)
    
    if args.ymin is not None or args.ymax is not None:
        ax.set_ylim(bottom=args.ymin, top=args.ymax)
    
    # Show legend if multiple plots or labels provided
    if n_plots > 1 or args.labels:
        ax.legend()
    
    # Show grid
    if args.grid:
        ax.grid(True, alpha=0.3)
    
    # Save figure
    try:
        plt.tight_layout()
        plt.savefig(args.output_png, dpi=args.dpi, bbox_inches='tight')
        print(f"Plot saved to {args.output_png}")
    except Exception as e:
        print(f"Error saving plot: {e}")
        sys.exit(1)
    
    plt.close()


if __name__ == '__main__':
    main()
