#!/usr/bin/env bash
# ============================================================================
# Shared launcher for Figure 3 CHD test-mode GPU runs.
#
# Writes a complete input.toml into RESULTS_DIR (so bond_ignore_array is
# recorded with the run), then calls run.py. 1D IAM in PCD mode (not Ewald).
#
# Usage:
#   ./scripts/bash/run_fig3_common.sh --qmax 4 --qlen 41 --ring open
#   ./scripts/bash/run_fig3_common.sh --qmax 8 --qlen 81 --ring closed
#   ./scripts/bash/run_fig3_qmax4_open.sh --comment rerun2
#
# Results directory (default results_fig3_qmax<X>_<open|closed>):
#   --comment DETAIL   append _DETAIL (e.g. results_fig3_qmax4_open_rerun2)
#   RESULTS_DIR=path   full override (ignores --comment)
#
# Environment overrides (defaults shown):
#   PYTHON             python3
#   GPU_CHAINS         128
#   STARTING_XYZ       xyz/start.xyz
#   TARGET_FILE        xyz/target_20.xyz
#   COMMENT            (unset) same as --comment
#   RESULTS_DIR        (unset) auto from qmax/ring/comment
#   EXTRA_RUN_PY_ARGS  (unset) extra args appended to run.py
# ============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

PYTHON="${PYTHON:-python3}"
GPU_CHAINS="${GPU_CHAINS:-128}"
STARTING_XYZ="${STARTING_XYZ:-xyz/start.xyz}"
TARGET_FILE="${TARGET_FILE:-xyz/target_20.xyz}"
START_SDF="${START_SDF:-sdf/chd_start.sdf}"
REFERENCE_XYZ="${REFERENCE_XYZ:-xyz/chd_reference.xyz}"
EXTRA_RUN_PY_ARGS="${EXTRA_RUN_PY_ARGS:-}"
COMMENT="${COMMENT:-}"
RESULTS_DIR_OVERRIDE="${RESULTS_DIR:-}"

QMAX=""
QLEN=""
RING=""

usage() {
    sed -n '3,27p' "$0" | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --qmax)
            QMAX="${2:-}"
            shift 2
            ;;
        --qlen)
            QLEN="${2:-}"
            shift 2
            ;;
        --ring)
            RING="${2:-}"
            shift 2
            ;;
        --comment)
            COMMENT="${2:-}"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "ERROR: unknown argument: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

if [[ -z "$QMAX" || -z "$QLEN" || -z "$RING" ]]; then
    echo "ERROR: --qmax, --qlen, and --ring are required" >&2
    usage >&2
    exit 1
fi

case "$RING" in
    open)
        BOND_IGNORE="[[0, 5]]"
        ;;
    closed)
        BOND_IGNORE="[]"
        ;;
    *)
        echo "ERROR: --ring must be 'open' or 'closed' (got '$RING')" >&2
        exit 1
        ;;
esac

COMMENT="${COMMENT// /_}"
if [[ -n "$COMMENT" && ! "$COMMENT" =~ ^[A-Za-z0-9._-]+$ ]]; then
    echo "ERROR: --comment must be a simple token (letters, digits, . _ -); got '$COMMENT'" >&2
    exit 1
fi

if [[ -n "$RESULTS_DIR_OVERRIDE" ]]; then
    RESULTS_DIR="$RESULTS_DIR_OVERRIDE"
else
    RESULTS_DIR="results_fig3_qmax${QMAX}_${RING}"
    if [[ -n "$COMMENT" ]]; then
        RESULTS_DIR="${RESULTS_DIR}_${COMMENT}"
    fi
fi
RUN_ID="fig3_qmax${QMAX}_${RING}${COMMENT:+_${COMMENT}}"

if [[ ! -f "$STARTING_XYZ" ]]; then
    echo "ERROR: STARTING_XYZ='$STARTING_XYZ' does not exist" >&2
    exit 1
fi
if [[ ! -f "$TARGET_FILE" ]]; then
    echo "ERROR: TARGET_FILE='$TARGET_FILE' does not exist" >&2
    exit 1
fi

mkdir -p "$RESULTS_DIR"
CONFIG_OUT="${RESULTS_DIR}/input.toml"

cat > "$CONFIG_OUT" <<EOF
# Figure 3 CHD test-mode GPU run: qmax=${QMAX}, ring=${RING}${COMMENT:+, comment=${COMMENT}}
# Generated by scripts/bash/run_fig3_common.sh — do not edit as a source of truth.
mode = "test"

[run_params]
run_id = "${RUN_ID}"
molecule = "chd"
results_dir = "${RESULTS_DIR}"

[files]
forcefield_file = "forcefields/openff_unconstrained-2.0.0.offxml"
start_xyz_file = "${STARTING_XYZ}"
start_sdf_file = "${START_SDF}"
reference_xyz_file = "${REFERENCE_XYZ}"
target_file = "${TARGET_FILE}"

[options]
run_pyscf_modes_bool = false
pyscf_basis = "6-31g**"
verbose_bool = false
write_dat_file_bool = true
mm_param_method = "basic"
gpu_backend = "cuda"
gpu_emulation_bool = false
gpu_chains = ${GPU_CHAINS}
restart_from_global_best_bool = true

[sampling]
sampling_bool = true
boltzmann_temperature = 300.0

[scattering_params]
inelastic_bool = true
ion_mode_bool = false
pcd_mode_bool = true
excitation_factor = 1.0

[scattering_params.q]
qmin = 0.0
qmax = ${QMAX}.0
qlen = ${QLEN}

[scattering_params.ewald]
ewald_mode_bool = false

[scattering_params.ewald.th]
tmin = 0.0
tmax = 1.0
tlen = 21

[scattering_params.ewald.ph]
pmin = 0.0
pmax = 2.0
plen = 21

[scattering_params.noise]
noise_value = 0.0
noise_data_file = "data/noise.dat"

[simulated_annealing_params]
sa_starting_temp = 1.0
sa_nsteps = 4000
greedy_algorithm_bool = true
ga_nsteps = 8000
sa_step_size = 0.025
ga_step_size = 0.025
nrestarts = 1
ntotalruns = 1
bonds_bool = true
angles_bool = true
torsions_bool = true
tuning_ratio_target = 0.5
c_tuning_initial = 0.1
signal_only_mode_bool = false
n_tuning_update_freq = 100
non_h_modes_only_bool = false
hydrogen_mode_damping_factor = 0.2
hydrogen_force_constant_scale = 1.0
hf_energy_bool = false

[molecule_params]
natoms = 14
nmodes = 36
hydrogen_mode_range = [28, 36]
sa_mode_range = [0, 36]
ga_mode_range = [0, 36]
bond_ignore_array = ${BOND_IGNORE}
angle_ignore_array = []
torsion_ignore_array = []
rmsd_indices = [0, 1, 2, 3, 4, 5]
bond_indices = [0, 5]
angle_indices = [0, 3, 5]
dihedral_indices = [0, 1, 4, 5]
EOF

echo "=== Figure 3 run ==="
echo "  ring           = $RING  (bond_ignore_array = $BOND_IGNORE)"
echo "  q              = 0.0 .. ${QMAX}.0  (${QLEN} pts)"
echo "  pcd_mode       = true  (IAM vs $REFERENCE_XYZ)"
echo "  comment        = ${COMMENT:-<none>}"
echo "  gpu_chains     = $GPU_CHAINS"
echo "  target         = $TARGET_FILE"
echo "  start          = $STARTING_XYZ"
echo "  results_dir    = $RESULTS_DIR"
echo "  config         = $CONFIG_OUT"

RUN_CMD=(
    "$PYTHON" run.py
    --config "$CONFIG_OUT"
    --mode test
    --run-id "$RUN_ID"
    --results-dir "$RESULTS_DIR"
    --start-xyz-file "$STARTING_XYZ"
    --target-file "$TARGET_FILE"
    --gpu-backend cuda
    --gpu-chains "$GPU_CHAINS"
    --restart-from-global-best
    --sampling
    --boltzmann-temperature 300.0
    --pcd-mode
    --qmin 0.0
    --qmax "$QMAX"
    --qlen "$QLEN"
    --sa-starting-temp 1.0
    --sa-nsteps 4000
    --greedy-algorithm
    --ga-nsteps 8000
    --sa-step-size 0.025
    --ga-step-size 0.025
    --nrestarts 1
    --ntotalruns 1
    --bonds
    --angles
    --torsions
    --tuning-ratio-target 0.5
    --c-tuning-initial 0.1
    --n-tuning-update-freq 100
)

if [[ -f "$START_SDF" ]]; then
    RUN_CMD+=(--start-sdf-file "$START_SDF")
fi
if [[ -f "$REFERENCE_XYZ" ]]; then
    RUN_CMD+=(--reference-xyz-file "$REFERENCE_XYZ")
fi

# shellcheck disable=SC2206
RUN_CMD+=( ${EXTRA_RUN_PY_ARGS} )
"${RUN_CMD[@]}"
